### ISSUE TITLE
missing build deps though I have them installed when building with pyproject.toml

### ISSUE THREAD

**Issue by hubutui** [KaveIO/PhiK#50]
step to build
```bash
cd PhiK-0.12.2
python -m build --wheel --no-isolation
```
logs:
```text
* Getting dependencies for wheel...
running egg_info
creating phik.egg-info
writing phik.egg-info/PKG-INFO
writing dependency_links to phik.egg-info/dependency_links.txt
writing entry points to phik.egg-info/entry_points.txt
writing requirements to phik.egg-info/requires.txt
writing top-level names to phik.egg-info/top_level.txt
writing manifest file 'phik.egg-info/SOURCES.txt'
reading manifest file 'phik.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files found matching 'docs'
warning: no previously-included files found matching 'tests'
warning: no previously-included files found matching '.readthedocs.yml'
warning: no previously-included files matching '*.py' found under directory 'tests'
adding license file 'LICENSE'
adding license file 'NOTICE'
writing manifest file 'phik.egg-info/SOURCES.txt'

ERROR Missing dependencies:
        cmake>=3.16
        ninja; platform_system!='Windows'
```
* OS: ArchLinux
* Python 3.10.2
* GCC 11.2.0
* python-scikit-build 0.13.1
* ninja 1.10.2
* cmake 3.22.3
* pybind11 1.9.1
I could build it with:
```bash
python -m build --wheel --no-isolation --skip-dependency-check
```

Also, these files are installed, comparing to version 0.12.0:
```text
/usr/CMakeLists.txt
/usr/LICENSE
/usr/NOTICE
/usr/README.rst
/usr/pyproject.toml
/usr/setup.py
```
I don't this the pkg should installed these files in this place.

**Comment by RUrlus** [comment]
hi @hubutui, thanks for reporting.

Your pybind11 version is too low, pybind11>=2.8.1 is the minimum required version.
With the correct versions I can't replicate the same issue with `python -m build --wheel --no-isolation` locally.

The commands above won't install anything but just create wheels, I think those files ended up in /usr/ due to some non-standard way of installing. We certainly don't do anything with setting the installation path

**Comment by hubutui** [comment]
@RUrlus sorry for the typo, we have `pybind11 2.9.1` installed. I'm creating pkg for ArchLinux according to [this guide](https://wiki.archlinux.org/title/Python_package_guidelines).
```bash
# create the wheel
python -m build --wheel --no-isolation
# and install
python -m installer --destdir="$pkgdir" dist/*.whl
```
the error log complains `cmake` and `ninja`, not `pybind11`.

**Comment by hubutui** [comment]
It seems the whl file ships some unneeded files.
I create a python 3.10 virtual env with conda, and install phik with `pip install phik`. I found `_skbuild` dir in the env dir
```text
~/.conda/envs/ENVNAME/_skbuild
```

**Comment by RUrlus** [comment]
@hubutui did you install cmake and ninja through pip or through a system manager?
I suspect it's a local issue rather than with the pyproject.toml. I can't replicate the behaviour with pip installed ninja/cmake.

> I found _skbuild dir in the env dir

Thanks for letting us know, strange it gets included. I'll have a look at excluding it

**Comment by hubutui** [comment]
what about these files:
```text
~/.conda/envs/ENVNAME/CMakeLists.txt
~/.conda/envs/ENVNAME/LICENSE
~/.conda/envs/ENVNAME/NOTICE
~/.conda/envs/ENVNAME/README.rst
~/.conda/envs/ENVNAME/pyproject.toml
~/.conda/envs/ENVNAME/setup.py
```
maybe:
```text
~/.conda/envs/ENVNAME/share/licenses/phik/LICENSE
~/.conda/envs/ENVNAME/share/licenses/phik/NOTICE
~/.conda/envs/ENVNAME/share/doc/LICENSE
```
and `setup.py, pyproject.toml, CMakeLists.txt` should not be shipped with the pkg.

**Comment by RUrlus** [comment]
Unfortunately it seems we're running into an [upstream issue](https://github.com/scikit-build/scikit-build/issues/680) in Scikit-build. You're right that these files should not be in the data directory.

**Comment by hubutui** [comment]
No, but I'm ok to build it with:
```bash
python -m build --wheel --no-isolation --skip-dependency-check
```

**Comment by hubutui** [comment]
Maybe we should not add `ninja` and `cmake` to `pyproject.toml`. It means we need to find a cmake and ninja from PyPI, aka a python package, not cmake and ninja.
I don't think people would install cmake from [PyPI](https://pypi.org/project/cmake/).

**Comment by RUrlus** [comment]
@hubutui the fix for the unneeded files is to remove the MANIFEST.in. We'll create a new release soon.

Regarding the pyproject.toml, I disagree. Many people (will) use the pip distributed cmake and ninja.
Moreover, building without isolation is non-standard these days.
I don't want to require people to install software manually when we can pip install it during the installation.

**Comment by hubutui** [comment]
ok, I think I'm ok to build it with `--skip-dependency-check`.
