### ISSUE TITLE
Arm

### ISSUE THREAD

**Issue by chunbaisikio** [KaveIO/PhiK#88]
I have an offline server with an ARM64 architecture, and while trying to install PhiK, I discovered that there are no compatible whl packages available on PyPI. Upon attempting to install from source code, I encountered errors. Could you please provide a whl package for arm64_linux or advise on which toolkits are required during the source code installation process?

**Comment by RUrlus** [comment]
Hi @chunbaisikio, aarch64 wheels are a pain because they need emulation and very few people use them.
You should be able to compile if you have a C++ 14 compliant compiler.
If the errors are coming from the installation of Phik and not the installation of one of our dependencies please post the errors here.
